### ISSUE TITLE
the page shows 404

### ISSUE THREAD

**Issue by zxqian1991** [OSBI/saiku_community_website#8]
i am sorry here to bother you...but,i have some problem in the website : http://community.meteorite.bi/docs/  , it seems that the docs page is 404, how can i read the docs in other way..thank you.

**Comment by brenopolanski** [comment]
Hey @zxqian1991 the same thread was discussed here: https://groups.google.com/a/saiku.meteorite.bi/forum/#!topic/user/0AqdDr8ifcE
