### ISSUE TITLE
Error downloading CE version of saiku plugin for Pentaho

### ISSUE THREAD

**Issue by virivigio** [OSBI/saiku_community_website#9]
Hi, the pentaho marketplace stopped working, I don't know who's in charge of notifying URL for components but actually this thread explain the error.
https://community.hitachivantara.com/thread/15031-how-to-add-saiku-analytics-plugin-in-pentaho-bi-server-81-error-in-installing-plugin
Please fix it otherwise it will be a barried to community version adoption
Regards
Virgilio

**Comment by brenopolanski** [comment]
Hey @virivigio 

You must create move this issue to https://github.com/OSBI/saiku/issues
